In [1]:
import tensorflow as tf
import numpy as np

In [44]:
data = 'help'
char2idx = {'h':0, 'e':1, 'l':2, 'p':3}
idx2char = {v : k for k, v in char2idx.items()}

In [45]:
char2idx

{'h': 0, 'e': 1, 'l': 2, 'p': 3}

In [46]:
idx2char


{0: 'h', 1: 'e', 2: 'l', 3: 'p'}

In [47]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data[1:]]

In [48]:
input_seq

[0, 1, 2]

In [49]:
target_seq

[1, 2, 3]

In [50]:
x = tf.one_hot(input_seq, depth=len(char2idx))
x = tf.expand_dims(x, axis=0)
y = tf.expand_dims(target_seq, axis=0)

In [51]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [52]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [53]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(8,return_sequences=True , input_shape =(3,4) ) , 
    tf.keras.layers.Dense(4,activation='linear')
    ])

In [54]:
model.compile(
    optimizer='adam' ,loss = tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True
    )
)

In [55]:
for epoch in range(501):
    model.train_on_batch(x,y)
    
    if epoch % 50  == 0 :
        output = model(x)
        pred = tf.argmax(output,axis = -1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred] )
        print(f"epoch : {epoch} , prediction : {pred_char} , loss : {loss} ")

epoch : 0 , prediction : eep , loss : 0.7125089764595032 
epoch : 50 , prediction : eep , loss : 0.7125089764595032 
epoch : 100 , prediction : epp , loss : 0.7125089764595032 
epoch : 150 , prediction : epp , loss : 0.7125089764595032 
epoch : 200 , prediction : elp , loss : 0.7125089764595032 
epoch : 250 , prediction : elp , loss : 0.7125089764595032 
epoch : 300 , prediction : elp , loss : 0.7125089764595032 
epoch : 350 , prediction : elp , loss : 0.7125089764595032 
epoch : 400 , prediction : elp , loss : 0.7125089764595032 
epoch : 450 , prediction : elp , loss : 0.7125089764595032 
epoch : 500 , prediction : elp , loss : 0.7125089764595032 
